name: Main CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: "1.10.3.855"


      - name: Test runner
        env:
          TESTOPT: "-X:test:test-runner"
        run: |
          cd library-for-github
          clojure $TESTOPT


      - name: Job digest -> telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          cd library-for-github
          clojure -X:test github.core.alpha.actions-helper.telegram/send-job-digest
